/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'forex' : IDL.Null,
  'crypto' : IDL.Null,
});
export const SignalType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const EducationResource = IDL.Record({
  'id' : IDL.Nat,
  'difficultyLevel' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'description' : IDL.Text,
  'category' : Category,
});
export const Signal = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null }),
  'pair' : IDL.Text,
  'target' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'timestamp' : IDL.Int,
  'category' : Category,
  'entryPrice' : IDL.Float64,
  'signalType' : SignalType,
});
export const SubmissionId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : SubmissionId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addEducationResource' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addSignal' : IDL.Func(
      [IDL.Text, SignalType, IDL.Float64, IDL.Float64, IDL.Float64, Category],
      [],
      [],
    ),
  'getAllEducationResources' : IDL.Func(
      [],
      [IDL.Vec(EducationResource)],
      ['query'],
    ),
  'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getContactSubmissionsByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getSignalsByCategory' : IDL.Func([Category], [IDL.Vec(Signal)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateEducationResource' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Category, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateSignal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        SignalType,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null }),
        Category,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({ 'forex' : IDL.Null, 'crypto' : IDL.Null });
  const SignalType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const EducationResource = IDL.Record({
    'id' : IDL.Nat,
    'difficultyLevel' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'description' : IDL.Text,
    'category' : Category,
  });
  const Signal = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null }),
    'pair' : IDL.Text,
    'target' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'timestamp' : IDL.Int,
    'category' : Category,
    'entryPrice' : IDL.Float64,
    'signalType' : SignalType,
  });
  const SubmissionId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : SubmissionId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addEducationResource' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addSignal' : IDL.Func(
        [IDL.Text, SignalType, IDL.Float64, IDL.Float64, IDL.Float64, Category],
        [],
        [],
      ),
    'getAllEducationResources' : IDL.Func(
        [],
        [IDL.Vec(EducationResource)],
        ['query'],
      ),
    'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getContactSubmissionsByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getSignalsByCategory' : IDL.Func([Category], [IDL.Vec(Signal)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateEducationResource' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Category, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateSignal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          SignalType,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null }),
          Category,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };