/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'forex' : null } |
  { 'crypto' : null };
export interface ContactSubmission {
  'id' : SubmissionId,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface EducationResource {
  'id' : bigint,
  'difficultyLevel' : string,
  'title' : string,
  'duration' : bigint,
  'description' : string,
  'category' : Category,
}
export interface Signal {
  'id' : bigint,
  'status' : { 'closed' : null } |
    { 'active' : null },
  'pair' : string,
  'target' : number,
  'stopLoss' : number,
  'timestamp' : bigint,
  'category' : Category,
  'entryPrice' : number,
  'signalType' : SignalType,
}
export type SignalType = { 'buy' : null } |
  { 'sell' : null };
export type SubmissionId = bigint;
export interface _SERVICE {
  'addEducationResource' : ActorMethod<
    [string, string, Category, string, bigint],
    undefined
  >,
  'addSignal' : ActorMethod<
    [string, SignalType, number, number, number, Category],
    undefined
  >,
  'getAllEducationResources' : ActorMethod<[], Array<EducationResource>>,
  'getAllSignals' : ActorMethod<[], Array<Signal>>,
  'getContactSubmissionsByEmail' : ActorMethod<
    [string],
    Array<ContactSubmission>
  >,
  'getSignalsByCategory' : ActorMethod<[Category], Array<Signal>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateEducationResource' : ActorMethod<
    [bigint, string, string, Category, string, bigint],
    undefined
  >,
  'updateSignal' : ActorMethod<
    [
      bigint,
      string,
      SignalType,
      number,
      number,
      number,
      { 'closed' : null } |
        { 'active' : null },
      Category,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];