/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    id: bigint;
    status: Variant_closed_active;
    pair: string;
    target: number;
    stopLoss: number;
    timestamp: bigint;
    category: Category;
    entryPrice: number;
    signalType: SignalType;
}
export interface EducationResource {
    id: bigint;
    difficultyLevel: string;
    title: string;
    duration: bigint;
    description: string;
    category: Category;
}
export interface ContactSubmission {
    id: SubmissionId;
    subject: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
}
export type SubmissionId = bigint;
export enum Category {
    forex = "forex",
    crypto = "crypto"
}
export enum SignalType {
    buy = "buy",
    sell = "sell"
}
export enum Variant_closed_active {
    closed = "closed",
    active = "active"
}
export interface backendInterface {
    addEducationResource(title: string, description: string, category: Category, difficultyLevel: string, duration: bigint): Promise<void>;
    addSignal(pair: string, signalType: SignalType, entryPrice: number, target: number, stopLoss: number, category: Category): Promise<void>;
    getAllEducationResources(): Promise<Array<EducationResource>>;
    getAllSignals(): Promise<Array<Signal>>;
    getContactSubmissionsByEmail(email: string): Promise<Array<ContactSubmission>>;
    getSignalsByCategory(category: Category): Promise<Array<Signal>>;
    submitContactForm(name: string, email: string, subject: string, message: string): Promise<void>;
    updateEducationResource(id: bigint, title: string, description: string, category: Category, difficultyLevel: string, duration: bigint): Promise<void>;
    updateSignal(id: bigint, pair: string, signalType: SignalType, entryPrice: number, target: number, stopLoss: number, status: Variant_closed_active, category: Category): Promise<void>;
}
import type { Category as _Category, EducationResource as _EducationResource, Signal as _Signal, SignalType as _SignalType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEducationResource(arg0: string, arg1: string, arg2: Category, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEducationResource(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEducationResource(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async addSignal(arg0: string, arg1: SignalType, arg2: number, arg3: number, arg4: number, arg5: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSignal(arg0, to_candid_SignalType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSignal(arg0, to_candid_SignalType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async getAllEducationResources(): Promise<Array<EducationResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEducationResources();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEducationResources();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSignals();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSignals();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissionsByEmail(arg0: string): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissionsByEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissionsByEmail(arg0);
            return result;
        }
    }
    async getSignalsByCategory(arg0: Category): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateEducationResource(arg0: bigint, arg1: string, arg2: string, arg3: Category, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEducationResource(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEducationResource(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async updateSignal(arg0: bigint, arg1: string, arg2: SignalType, arg3: number, arg4: number, arg5: number, arg6: Variant_closed_active, arg7: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignal(arg0, arg1, to_candid_SignalType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg6), to_candid_Category_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignal(arg0, arg1, to_candid_SignalType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg6), to_candid_Category_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_Category_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_EducationResource_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationResource): EducationResource {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SignalType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalType): SignalType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        closed: null;
    } | {
        active: null;
    };
    pair: string;
    target: number;
    stopLoss: number;
    timestamp: bigint;
    category: _Category;
    entryPrice: number;
    signalType: _SignalType;
}): {
    id: bigint;
    status: Variant_closed_active;
    pair: string;
    target: number;
    stopLoss: number;
    timestamp: bigint;
    category: Category;
    entryPrice: number;
    signalType: SignalType;
} {
    return {
        id: value.id,
        status: from_candid_variant_n13(_uploadFile, _downloadFile, value.status),
        pair: value.pair,
        target: value.target,
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        category: from_candid_Category_n8(_uploadFile, _downloadFile, value.category),
        entryPrice: value.entryPrice,
        signalType: from_candid_SignalType_n14(_uploadFile, _downloadFile, value.signalType)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficultyLevel: string;
    title: string;
    duration: bigint;
    description: string;
    category: _Category;
}): {
    id: bigint;
    difficultyLevel: string;
    title: string;
    duration: bigint;
    description: string;
    category: Category;
} {
    return {
        id: value.id,
        difficultyLevel: value.difficultyLevel,
        title: value.title,
        duration: value.duration,
        description: value.description,
        category: from_candid_Category_n8(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    active: null;
}): Variant_closed_active {
    return "closed" in value ? Variant_closed_active.closed : "active" in value ? Variant_closed_active.active : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): SignalType {
    return "buy" in value ? SignalType.buy : "sell" in value ? SignalType.sell : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forex: null;
} | {
    crypto: null;
}): Category {
    return "forex" in value ? Category.forex : "crypto" in value ? Category.crypto : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Signal>): Array<Signal> {
    return value.map((x)=>from_candid_Signal_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EducationResource>): Array<EducationResource> {
    return value.map((x)=>from_candid_EducationResource_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SignalType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType): _SignalType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_closed_active): {
    closed: null;
} | {
    active: null;
} {
    return value == Variant_closed_active.closed ? {
        closed: null
    } : value == Variant_closed_active.active ? {
        active: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    forex: null;
} | {
    crypto: null;
} {
    return value == Category.forex ? {
        forex: null
    } : value == Category.crypto ? {
        crypto: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType): {
    buy: null;
} | {
    sell: null;
} {
    return value == SignalType.buy ? {
        buy: null
    } : value == SignalType.sell ? {
        sell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
